services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kino
      POSTGRES_USER: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports: # Для разработки прокидуется ссылка для подключения в не контейнера
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"] # Для разработки слушает все порты
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  app:
    build:
      dockerfile: /Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ./backend/src/:/app/src/
    command: ["sh", "-c", "alembic upgrade head  && poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000"]
    # TODO: изменить пути и вызовы
volumes:
  pg_data:
  pgadmin_data: