services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kino
      POSTGRES_USER: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy
  app:
    build:
      dockerfile: /Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy