# Требуется стандартизировать настройки и ограничить некоторые параметры
services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kino
      POSTGRES_USER: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports: # Для разработки прокидуется ссылка для подключения в не контейнера
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"] # Для разработки слушает все порты
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  # Требуется добавить healthcheck
  auth:
    build:
      dockerfile: /Dockerfile
      context: ./backend/src/apps/auth
    
    # Порты для доступа если требуется
    # ports:
    #   - "8002:8001"
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ./backend/src/apps/auth/app:/app/app
    command: ["sh", "-c", "alembic upgrade head  && poetry run python -m uvicorn main:setup_start_test_app --host 0.0.0.0 --port 8001"]
  api-getaway:
    build:
      context: ./backend/src/apps/apigetaway
      dockerfile: /Dockerfile
    ports:
     - "8000:8000"
    volumes:
      - ./backend/src/apps/apigetaway/app:/app/app
    command: ["sh", "-c", "poetry run python -m uvicorn main:start_app_dev --port 8000 --host 0.0.0.0 --factory --reload"]

networks:
  default:
    driver: bridge
volumes:
  pg_data:
  pgadmin_data: