"""add username and time create

Revision ID: 4ad702834146
Revises: e6c9647ef3eb
Create Date: 2025-07-28 15:09:19.701844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ad702834146"
down_revision: Union[str, Sequence[str], None] = "e6c9647ef3eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("create_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=False)
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("users", "create_at")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
