from app.application.commands.documents import (
    UploadShiftDocumentCommand,
    UploadShiftDocumentHandler,
)
from app.application.commands.reservation_outbox import ProcessReservationOutboxHandler
from app.application.commands.participants import (
    ConfirmShiftParticipantCommand,
    ConfirmShiftParticipantHandler,
    DeclineShiftParticipantCommand,
    DeclineShiftParticipantHandler,
    InviteShiftParticipantCommand,
    InviteShiftParticipantHandler,
)
from app.application.commands.projects import (
    ApproveProjectMemberInvitationCommand,
    ApproveProjectMemberInvitationHandler,
    ChangeProjectMemberRoleCommand,
    ChangeProjectMemberRoleHandler,
    CreateProjectCommand,
    CreateProjectHandler,
    DeleteProjectCommand,
    DeleteProjectHandler,
    InviteProjectMemberCommand,
    InviteProjectMemberHandler,
    RemoveProjectMemberCommand,
    RemoveProjectMemberHandler,
    UpdateProjectCommand,
    UpdateProjectHandler,
)
from app.application.commands.resources import (
    ApproveResourceRequestCommand,
    ApproveResourceRequestHandler,
    CreateResourceRequestCommand,
    CreateResourceRequestHandler,
    RejectResourceRequestCommand,
    RejectResourceRequestHandler,
)
from app.application.commands.shifts import (
    ApproveShiftCommand,
    ApproveShiftHandler,
    CreateShiftCommand,
    CreateShiftHandler,
)

__all__ = [
    "CreateProjectCommand",
    "CreateProjectHandler",
    "DeleteProjectCommand",
    "DeleteProjectHandler",
    "UpdateProjectCommand",
    "UpdateProjectHandler",
    "InviteProjectMemberCommand",
    "InviteProjectMemberHandler",
    "ChangeProjectMemberRoleCommand",
    "ChangeProjectMemberRoleHandler",
    "ApproveProjectMemberInvitationCommand",
    "ApproveProjectMemberInvitationHandler",
    "RemoveProjectMemberCommand",
    "RemoveProjectMemberHandler",
    "CreateShiftCommand",
    "CreateShiftHandler",
    "ApproveShiftCommand",
    "ApproveShiftHandler",
    "InviteShiftParticipantCommand",
    "InviteShiftParticipantHandler",
    "ConfirmShiftParticipantCommand",
    "ConfirmShiftParticipantHandler",
    "DeclineShiftParticipantCommand",
    "DeclineShiftParticipantHandler",
    "UploadShiftDocumentCommand",
    "UploadShiftDocumentHandler",
    "ProcessReservationOutboxHandler",
    "CreateResourceRequestCommand",
    "CreateResourceRequestHandler",
    "ApproveResourceRequestCommand",
    "ApproveResourceRequestHandler",
    "RejectResourceRequestCommand",
    "RejectResourceRequestHandler",
]
