"""add free times

Revision ID: 672045836ce9
Revises: b6a364d778fe
Create Date: 2026-02-15 16:14:04.139240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '672045836ce9'
down_revision: Union[str, Sequence[str], None] = 'b6a364d778fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_users_timing',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.oid'], name=op.f('fk_free_users_timing_user_id_users')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_free_users_timing'))
    )
    op.create_table('camera_free_times',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.oid'], name=op.f('fk_camera_free_times_camera_id_cameras')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_camera_free_times'))
    )
    op.create_table('camera_tripod_free_times',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('camera_tripod_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['camera_tripod_id'], ['camera_tripods.oid'], name=op.f('fk_camera_tripod_free_times_camera_tripod_id_camera_tripods')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_camera_tripod_free_times'))
    )
    op.create_table('light_free_times',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('light_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['light_id'], ['lights.oid'], name=op.f('fk_light_free_times_light_id_lights')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_light_free_times'))
    )
    op.create_table('light_tripod_free_times',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('light_tripod_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['light_tripod_id'], ['light_tripods.oid'], name=op.f('fk_light_tripod_free_times_light_tripod_id_light_tripods')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_light_tripod_free_times'))
    )
    op.create_table('microfon_free_times',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('microfon_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['microfon_id'], ['microfons.oid'], name=op.f('fk_microfon_free_times_microfon_id_microfons')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_microfon_free_times'))
    )
    op.create_table('requisite_free_times',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('requisite_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['requisite_id'], ['requisites.oid'], name=op.f('fk_requisite_free_times_requisite_id_requisites')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_requisite_free_times'))
    )
    op.create_table('sound_free_times',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('sound_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sound_id'], ['sounds.oid'], name=op.f('fk_sound_free_times_sound_id_sounds')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_sound_free_times'))
    )
    op.drop_table('spare_times')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_times',
    sa.Column('oid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('obj', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('oid', name=op.f('spare_times_pkey'))
    )
    op.drop_table('sound_free_times')
    op.drop_table('requisite_free_times')
    op.drop_table('microfon_free_times')
    op.drop_table('light_tripod_free_times')
    op.drop_table('light_free_times')
    op.drop_table('camera_tripod_free_times')
    op.drop_table('camera_free_times')
    op.drop_table('free_users_timing')
    # ### end Alembic commands ###
