"""update re relationships

Revision ID: b6a364d778fe
Revises: 59ddd0f24011
Create Date: 2026-01-26 17:09:44.779303

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b6a364d778fe"
down_revision: Union[str, Sequence[str], None] = "59ddd0f24011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_camera_tripods_users_id_users"),
        "camera_tripods",
        "users",
        ["users_id"],
        ["oid"],
    )
    op.create_foreign_key(
        op.f("fk_cameras_users_id_users"), "cameras", "users", ["users_id"], ["oid"]
    )
    op.drop_constraint(op.f("descriptions_user_id_key"), "descriptions", type_="unique")
    op.create_unique_constraint(
        op.f("uq_descriptions_user_id"), "descriptions", ["user_id"]
    )
    op.create_foreign_key(
        op.f("fk_descriptions_user_id_users"),
        "descriptions",
        "users",
        ["user_id"],
        ["oid"],
    )
    op.create_foreign_key(
        op.f("fk_images_requisite_id_requisites"),
        "images",
        "requisites",
        ["requisite_id"],
        ["oid"],
    )
    op.create_foreign_key(
        op.f("fk_light_tripods_users_id_users"),
        "light_tripods",
        "users",
        ["users_id"],
        ["oid"],
    )
    op.create_foreign_key(
        op.f("fk_lights_users_id_users"), "lights", "users", ["users_id"], ["oid"]
    )
    op.create_foreign_key(
        op.f("fk_microfons_users_id_users"), "microfons", "users", ["users_id"], ["oid"]
    )
    op.create_foreign_key(
        op.f("fk_requisites_users_id_users"),
        "requisites",
        "users",
        ["users_id"],
        ["oid"],
    )
    op.create_foreign_key(
        op.f("fk_sounds_users_id_users"), "sounds", "users", ["users_id"], ["oid"]
    )
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint(op.f("fk_sounds_users_id_users"), "sounds", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_requisites_users_id_users"), "requisites", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_microfons_users_id_users"), "microfons", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_lights_users_id_users"), "lights", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_light_tripods_users_id_users"), "light_tripods", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_images_requisite_id_requisites"), "images", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_descriptions_user_id_users"), "descriptions", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_descriptions_user_id"), "descriptions", type_="unique")
    op.create_unique_constraint(
        op.f("descriptions_user_id_key"),
        "descriptions",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("fk_cameras_users_id_users"), "cameras", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_camera_tripods_users_id_users"), "camera_tripods", type_="foreignkey"
    )
    # ### end Alembic commands ###
