from app.application.commands.base import Command, CommandHandler
from app.application.commands.create_microfon import (
    CreateMicrofonCommand,
    CreateMicrofonHandler,
)
from app.application.commands.create_description import (
    CreateDescriptionCommand,
    CreateDescriptionHandler,
)
from app.application.commands.update_description import (
    UpdateDescriptionCommand,
    UpdateDescriptionHandler,
)
from app.application.commands.add_spare_time import (
    AddSpareTimeCommand,
    AddSpareTimeHandler,
)
from app.application.commands.reserve_availability import (
    ReserveAvailabilityCommand,
    ReserveAvailabilityHandler,
)
from app.application.commands.add_image import AddImageCommand, AddImageHandler
from app.application.commands.remove_image import RemoveImageCommand, RemoveImageHandler
from app.application.commands.create_equipment import (
    CreateCameraCommand,
    CreateCameraHandler,
    CreateCameraTripodCommand,
    CreateCameraTripodHandler,
    CreateLightCommand,
    CreateLightHandler,
    CreateLightTripodCommand,
    CreateLightTripodHandler,
    CreateSoundCommand,
    CreateSoundHandler,
    CreateRequisiteCommand,
    CreateRequisiteHandler,
)
from app.application.commands.update_equipment import (
    UpdateMicrofonCommand,
    UpdateMicrofonHandler,
    UpdateCameraCommand,
    UpdateCameraHandler,
    UpdateCameraTripodCommand,
    UpdateCameraTripodHandler,
    UpdateLightCommand,
    UpdateLightHandler,
    UpdateLightTripodCommand,
    UpdateLightTripodHandler,
    UpdateSoundCommand,
    UpdateSoundHandler,
    UpdateRequisiteCommand,
    UpdateRequisiteHandler,
)
from app.application.commands.delete_equipment import (
    DeleteMicrofonCommand,
    DeleteMicrofonHandler,
    DeleteCameraCommand,
    DeleteCameraHandler,
    DeleteCameraTripodCommand,
    DeleteCameraTripodHandler,
    DeleteLightCommand,
    DeleteLightHandler,
    DeleteLightTripodCommand,
    DeleteLightTripodHandler,
    DeleteSoundCommand,
    DeleteSoundHandler,
    DeleteRequisiteCommand,
    DeleteRequisiteHandler,
)

__all__ = [
    "Command",
    "CommandHandler",
    "AddImageCommand",
    "AddImageHandler",
    "AddSpareTimeCommand",
    "AddSpareTimeHandler",
    "CreateCameraCommand",
    "CreateCameraHandler",
    "CreateCameraTripodCommand",
    "CreateCameraTripodHandler",
    "CreateDescriptionCommand",
    "CreateDescriptionHandler",
    "CreateLightCommand",
    "CreateLightHandler",
    "CreateLightTripodCommand",
    "CreateLightTripodHandler",
    "CreateMicrofonCommand",
    "CreateMicrofonHandler",
    "CreateRequisiteCommand",
    "CreateRequisiteHandler",
    "CreateSoundCommand",
    "CreateSoundHandler",
    "DeleteCameraCommand",
    "DeleteCameraHandler",
    "DeleteCameraTripodCommand",
    "DeleteCameraTripodHandler",
    "DeleteLightCommand",
    "DeleteLightHandler",
    "DeleteLightTripodCommand",
    "DeleteLightTripodHandler",
    "DeleteMicrofonCommand",
    "DeleteMicrofonHandler",
    "DeleteRequisiteCommand",
    "DeleteRequisiteHandler",
    "DeleteSoundCommand",
    "DeleteSoundHandler",
    "RemoveImageCommand",
    "RemoveImageHandler",
    "ReserveAvailabilityCommand",
    "ReserveAvailabilityHandler",
    "UpdateCameraCommand",
    "UpdateCameraHandler",
    "UpdateCameraTripodCommand",
    "UpdateCameraTripodHandler",
    "UpdateDescriptionCommand",
    "UpdateDescriptionHandler",
    "UpdateLightCommand",
    "UpdateLightHandler",
    "UpdateLightTripodCommand",
    "UpdateLightTripodHandler",
    "UpdateMicrofonCommand",
    "UpdateMicrofonHandler",
    "UpdateRequisiteCommand",
    "UpdateRequisiteHandler",
    "UpdateSoundCommand",
    "UpdateSoundHandler",
]
