"""shift reminder

Revision ID: 9416ddde1a58
Revises: 9d1c3a6b4f2e
Create Date: 2026-06-02 21:51:48.794365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9416ddde1a58'
down_revision: Union[str, Sequence[str], None] = '9d1c3a6b4f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_reminders',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_shift_reminders')),
    sa.UniqueConstraint('shift_id', name=op.f('uq_shift_reminders_shift_id'))
    )
    op.create_index(op.f('ix_shift_reminders_status'), 'shift_reminders', ['status', 'fire_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_reminders_status'), table_name='shift_reminders')
    op.drop_table('shift_reminders')
    # ### end Alembic commands ###
