"""start shemas

Revision ID: eb839239e502
Revises: 
Create Date: 2026-03-05 11:58:53.988643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb839239e502'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    op.create_index(op.f('ix_documents_shift_id'), 'documents', ['shift_id'], unique=False)
    op.create_table('projects',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('shift',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_shift'))
    )
    op.create_index(op.f('ix_shift_project_id'), 'shift', ['project_id'], unique=False)
    op.create_index(op.f('ix_shift_status'), 'shift', ['status'], unique=False)
    op.create_table('shift_participants',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('time_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('user_reservation_id', sa.Uuid(), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('reserve_failure_reason', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_shift_participants')),
    sa.UniqueConstraint('shift_id', 'user_id', name=op.f('uq_shift_participants_shift_id'))
    )
    op.create_index(op.f('ix_shift_participants_shift_id'), 'shift_participants', ['shift_id'], unique=False)
    op.create_index(op.f('ix_shift_participants_status'), 'shift_participants', ['status'], unique=False)
    op.create_index(op.f('ix_shift_participants_user_id'), 'shift_participants', ['user_id'], unique=False)
    op.create_table('shift_resource_requests',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('resource_owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('time_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('resource_reservation_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=2000), nullable=True),
    sa.Column('reserve_failure_reason', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_shift_resource_requests'))
    )
    op.create_index(op.f('ix_shift_resource_requests_project_id'), 'shift_resource_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_shift_resource_requests_resource_owner_user_id'), 'shift_resource_requests', ['resource_owner_user_id'], unique=False)
    op.create_index(op.f('ix_shift_resource_requests_shift_id'), 'shift_resource_requests', ['shift_id'], unique=False)
    op.create_index(op.f('ix_shift_resource_requests_status'), 'shift_resource_requests', ['status'], unique=False)
    op.create_table('users_project_role',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk_users_project_role')),
    sa.UniqueConstraint('project_id', 'user_id', name=op.f('uq_users_project_role_project_id'))
    )
    op.create_index(op.f('ix_users_project_role_project_id'), 'users_project_role', ['project_id'], unique=False)
    op.create_index(op.f('ix_users_project_role_user_id'), 'users_project_role', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_project_role_user_id'), table_name='users_project_role')
    op.drop_index(op.f('ix_users_project_role_project_id'), table_name='users_project_role')
    op.drop_table('users_project_role')
    op.drop_index(op.f('ix_shift_resource_requests_status'), table_name='shift_resource_requests')
    op.drop_index(op.f('ix_shift_resource_requests_shift_id'), table_name='shift_resource_requests')
    op.drop_index(op.f('ix_shift_resource_requests_resource_owner_user_id'), table_name='shift_resource_requests')
    op.drop_index(op.f('ix_shift_resource_requests_project_id'), table_name='shift_resource_requests')
    op.drop_table('shift_resource_requests')
    op.drop_index(op.f('ix_shift_participants_user_id'), table_name='shift_participants')
    op.drop_index(op.f('ix_shift_participants_status'), table_name='shift_participants')
    op.drop_index(op.f('ix_shift_participants_shift_id'), table_name='shift_participants')
    op.drop_table('shift_participants')
    op.drop_index(op.f('ix_shift_status'), table_name='shift')
    op.drop_index(op.f('ix_shift_project_id'), table_name='shift')
    op.drop_table('shift')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_documents_shift_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
